name: Flight Booking CICD

on:
  push:
    branches:
      #- dev
      #- main

permissions:
  id-token: write
  contents: read

jobs:
  upload-to-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to GCP using Workload Identity
      - id: auth
        uses: google-github-actions/auth@v2.0.0  
        with:
          workload_identity_provider: 'projects/611054035776/locations/global/workloadIdentityPools/flight-booking-cicd/providers/github'
          service_account: '611054035776-compute@developer.gserviceaccount.com'
      
      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      # Force correct project and clear conflicting env vars
      - name: Configure GCP Project
        run: |
          unset CLOUDSDK_CORE_PROJECT CLOUDSDK_PROJECT GCLOUD_PROJECT GCP_PROJECT GOOGLE_CLOUD_PROJECT
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config list

      # Upload `variables.json` to Composer bucket
      - name: Upload Variables JSON to GCS
        run: |
          unset CLOUDSDK_CORE_PROJECT CLOUDSDK_PROJECT GCLOUD_PROJECT GCP_PROJECT GOOGLE_CLOUD_PROJECT
          gsutil cp variables/dev/variables.json gs://europe-west1-airflow-dev-f6cb5223-bucket/data/dev/variables.json

      # Import Variables into Airflow-DEV
      - name: Import Variables into Airflow-DEV
        run: |
          gcloud composer environments run airflow-dev \
            --location europe-west1 \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            variables import -- /home/airflow/gcs/data/dev/variables.json

      # Upload Spark job to GCS
      - name: Upload Spark Job to GCS
        run: |
          unset CLOUDSDK_CORE_PROJECT CLOUDSDK_PROJECT GCLOUD_PROJECT GCP_PROJECT GOOGLE_CLOUD_PROJECT
          gsutil cp spark_job/spark_transformation_job.py gs://airflow-projects-bucket-v1/flight-booking-analysis/spark-job/

      # Upload Airflow DAG to Composer DEV
      - name: Upload Airflow DAG to DEV Environment
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-dev \
            --location europe-west1 \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --source airflow_job/airflow_job.py

  upload-to-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to GCP using Workload Identity
      - id: auth
        uses: google-github-actions/auth@v2.0.0  
        with:
          workload_identity_provider: 'projects/611054035776/locations/global/workloadIdentityPools/flight-booking-cicd/providers/github'
          service_account: '611054035776-compute@developer.gserviceaccount.com'

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Force correct project and clear conflicting env vars
      - name: Configure GCP Project
        run: |
          unset CLOUDSDK_CORE_PROJECT CLOUDSDK_PROJECT GCLOUD_PROJECT GCP_PROJECT GOOGLE_CLOUD_PROJECT
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config list

      # Upload `variables.json` to Composer bucket
      - name: Upload Variables JSON to GCS
        run: |
          unset CLOUDSDK_CORE_PROJECT CLOUDSDK_PROJECT GCLOUD_PROJECT GCP_PROJECT GOOGLE_CLOUD_PROJECT
          gsutil cp variables/prod/variables.json gs://europe-west1-airflow-prod-da5d4182-bucket/data/prod/variables.json

      # Import Variables into Airflow-PROD
      - name: Import Variables into Airflow-PROD
        run: |
          gcloud composer environments run airflow-prod \
            --location europe-west1 \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            variables import -- /home/airflow/gcs/data/prod/variables.json

      # Upload Spark job to GCS
      - name: Upload Spark Job to GCS
        run: |
          unset CLOUDSDK_CORE_PROJECT CLOUDSDK_PROJECT GCLOUD_PROJECT GCP_PROJECT GOOGLE_CLOUD_PROJECT
          gsutil cp spark_job/spark_transformation_job.py gs://airflow-projects-bucket-v1/flight-booking-analysis/spark-job/

      # Upload Airflow DAG to Composer PROD
      - name: Upload Airflow DAG to PROD Environment
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-prod \
            --location europe-west1 \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --source airflow_job/airflow_job.py